export const paths = {
  root: '/',
  login: '/login',
  dashboard: '/dashboard',
  monitoring: '/monitoring',
  monitoringShifts: '/monitoring/shifts',
  monitoringPumps: '/monitoring/pumps',
  monitoringTanks: '/monitoring/tanks',
  shiftDetails: (id: string) => `/monitoring/shifts/${id}`,
  fuelSales: '/fuel-sales',
  pumpTransactions: (id: string) => `/monitoring/pumps/${id}/transactions`,
  tankDetails: (id: string) => `/monitoring/tanks/${id}`,
  debtors: '/debtors',
  masterProducts: '/master/products',
  masterCategory: '/master/category',
  masterEmployees: '/master/employees',
  masterAttendants: '/master/attendants',
  reportsFuelSalesDetail: '/reports/fuel-sales-detail',
  reportsDailySalesSummary: '/reports/daily-sales-summary',
  reportsFuelSalesPump: '/reports/fuel-sales-pump',
  reportsSalesByAttendant: '/reports/sales-by-attendant',
  reportsFuelProfitReport: '/reports/fuel-profit-report',
  reportsTankVsPump: '/reports/tank-vs-pump',
  reportsShiftSheetReport: '/reports/shift-sheet-report',
  reportsFuelPurchases: '/reports/fuel-purchases',
  settings: '/settings',
  forecourtAuthorizePump: '/forecourt/authorize-pump',
  forecourtEmergencyStop: '/forecourt/emergency-stop',
  forecourtPriceChange: '/forecourt/price-change',
} as const;
